### ISSUE TITLE
Lingering Subscription Query registrations in AxonServer on "No Handler for query"

### ISSUE THREAD

**Issue by abuijze** [AxonIQ/axon-server-se#116]
When a component sends a subscript query for which there is no destination, it receives and error stating there is no handler for query. When starting a component that can handle this type of query, it immediately receives the subscriptions for the failed query, and the subscription queries are reported as "active" on the application's overview screen.
There is no way to get rid of these subscriptions other than restarting AxonServer.

**Comment by saratry** [comment]
Solved
