### ISSUE TITLE
AxonServer 4.4 does not publish first ever event to the projections

### ISSUE THREAD

**Issue by dmurat** [AxonIQ/axon-server-se#148]
After starting AxonServer 4.4 in clean (say via Docker), without any prior stored events, the first published event is not propagated to the projections. Second, and any following events are propagated correctly.

I'm experiencing this behavior after upgrading to Axon Framework 4.4 and Axon Server 4.4. Axon Framework 4.4 with Axon Server 4.3.5 works correctly.

Sorry for not having more details, but I wanted to give you heads up as soon as possible. If I'm correct, it should be easily reproducible.

Tnx.

**Comment by MGathier** [comment]
We are investigating the issue.

**Comment by MGathier** [comment]
This was an issue in Axon Framework 4.4 (in particular in the combination with Axon Server 4.4). We have fixed the issue and released version 4.4.1 of Axon Framework.

**Comment by dmurat** [comment]
FYI, I just tried Axon Framework 4.4.1 with Axon Server 4.4, and the issue is gone :-). Tnx

**Comment by smcvb** [comment]
Next for telling us this @dmurat, that's very much appreciated :bow:.
