### ISSUE TITLE
Add logging statement if dev-mode is enabled.

### ISSUE THREAD

**Issue by vab2048** [AxonIQ/axon-server-se#154]
Currently there is already a line which is logged when starting Axon Server 

```
2020-08-25 12:36:09.414  INFO 58788 --- [           main] A.i.a.a.c.MessagingPlatformConfiguration : Configuration initialized with SSL DISABLED and access control DISABLED.
```

Is it possible to either (a) add to this line, (b) log another line, to indicate if dev-mode has been enabled?
This is really just for convenience to avoid having to find out what command line arguments were used (`-Daxoniq.axonserver.devmode.enabled=true`) or whether the value was set in the properties file.

**Comment by MGathier** [comment]
Included in Axon Server SE version 4.6.6
