### ISSUE TITLE
Build failing due to snapshot dependency on server-api

### ISSUE THREAD

**Issue by jangalinski** [AxonIQ/axon-server-se#17]
build depends on 

```
<axonserver.api.version>4.2-SNAPSHOT</axonserver.api.version>
....
<dependency>
        <groupId>io.axoniq</groupId>
        <artifactId>axon-server-api</artifactId>
        <version>${axonserver.api.version}</version>
</dependency>
```

Since no snapshot repo is configured to resolve this dependency, a local build fails if you do not install the api snapshot before hand.

**Comment by zambrovski** [comment]
I tried to use the snapshots repository used in distribution management, but this is protected (getting Not authorized) even for public reading.

**Comment by jangalinski** [comment]
thanks!
