### ISSUE TITLE
Build of axonserver-query-parser fails, because of missing files

### ISSUE THREAD

**Issue by Niklas-Peter** [AxonIQ/axon-server-se#27]
What I did:

1. cloned the repository (I tried both master and axonserver-se-4.1.x branches)
2. opened in IntelliJ IDEA
3. build fails with the messages shown below

What is wrong?
I could really not find the classes like `EventStoreQueryBaseListener` in the GitHub repository.

`Information:java: Errors occurred while compiling module 'axonserver-query-parser'
Information:javac 12.0.1 was used to compile java sources
Information:Modules "axonserver-cli", "axonserver-grpc" were fully rebuilt due to project configuration/dependencies changes
Information:16.06.2019 17:49 - Build completed with 52 errors and 0 warnings in 3 s 547 ms
C:\Users\Niklas\Desktop\axon-server-se\axonserver-query-parser\src\main\java\io\axoniq\axonserver\queryparser\EventStoreQueryListener.java
    Error:Error:line (12)java: cannot find symbol
  symbol:   class EventStoreQueryBaseListener
  location: package io.axoniq
    Error:Error:line (13)java: cannot find symbol
  symbol:   class EventStoreQueryParser
  location: package io.axoniq
    Error:Error:line (21)java: cannot find symbol
  symbol: class EventStoreQueryBaseListener
    Error:Error:line (23)java: cannot find symbol
  symbol:   class EventStoreQueryParser
  location: package io.axoniq
    Error:Error:line (31)java: cannot find symbol
  symbol:   class QueryContext
  location: class io.axoniq.axonserver.queryparser.EventStoreQueryParser
    Error:Error:line (36)java: cannot find symbol
  symbol:   class QueryContext
  location: class io.axoniq.axonserver.queryparser.EventStoreQueryParser
    Error:Error:line (40)java: cannot find symbol
  symbol:   class Time_constraintContext
  location: class io.axoniq.axonserver.queryparser.EventStoreQueryParser
    Error:Error:line (73)java: cannot find symbol
  symbol:   class Time_constraintContext
  location: class io.axoniq.axonserver.queryparser.EventStoreQueryParser
    Error:Error:line (79)java: cannot find symbol
  symbol:   class Time_unitContext
  location: class io.axoniq.axonserver.queryparser.EventStoreQueryParser
    Error:Error:line (85)java: cannot find symbol
  symbol:   class ExprContext
  location: class io.axoniq.axonserver.queryparser.EventStoreQueryParser
    Error:Error:line (91)java: cannot find symbol
  symbol:   class ExprContext
  location: class io.axoniq.axonserver.queryparser.EventStoreQueryParser
    Error:Error:line (106)java: cannot find symbol
  symbol:   class Signed_numberContext
  location: class io.axoniq.axonserver.queryparser.EventStoreQueryParser
    Error:Error:line (111)java: cannot find symbol
  symbol:   class Literal_valueContext
  location: class io.axoniq.axonserver.queryparser.EventStoreQueryParser
    Error:Error:line (116)java: cannot find symbol
  symbol:   class IdentifierContext
  location: class io.axoniq.axonserver.queryparser.EventStoreQueryParser
    Error:Error:line (121)java: cannot find symbol
  symbol:   class Function_nameContext
  location: class io.axoniq.axonserver.queryparser.EventStoreQueryParser
    Error:Error:line (127)java: cannot find symbol
  symbol:   class Unary_operatorContext
  location: class io.axoniq.axonserver.queryparser.EventStoreQueryParser
    Error:Error:line (133)java: cannot find symbol
  symbol:   class Operator_group1Context
  location: class io.axoniq.axonserver.queryparser.EventStoreQueryParser
    Error:Error:line (139)java: cannot find symbol
  symbol:   class Operator_group2Context
  location: class io.axoniq.axonserver.queryparser.EventStoreQueryParser
    Error:Error:line (145)java: cannot find symbol
  symbol:   class Operator_group3Context
  location: class io.axoniq.axonserver.queryparser.EventStoreQueryParser
    Error:Error:line (151)java: cannot find symbol
  symbol:   class Operator_group4Context
  location: class io.axoniq.axonserver.queryparser.EventStoreQueryParser
    Error:Error:line (157)java: cannot find symbol
  symbol:   class Operator_group5Context
  location: class io.axoniq.axonserver.queryparser.EventStoreQueryParser
    Error:Error:line (163)java: cannot find symbol
  symbol:   class Operator_group6Context
  location: class io.axoniq.axonserver.queryparser.EventStoreQueryParser
    Error:Error:line (169)java: cannot find symbol
  symbol:   class AliasContext
  location: class io.axoniq.axonserver.queryparser.EventStoreQueryParser
    Error:Error:line (177)java: cannot find symbol
  symbol:   class Expr_listContext
  location: class io.axoniq.axonserver.queryparser.EventStoreQueryParser
    Error:Error:line (182)java: cannot find symbol
  symbol:   class Expr_listContext
  location: class io.axoniq.axonserver.queryparser.EventStoreQueryParser
    Error:Error:line (30)java: method does not override or implement a method from a supertype
    Error:Error:line (35)java: method does not override or implement a method from a supertype
    Error:Error:line (39)java: method does not override or implement a method from a supertype
    Error:Error:line (72)java: method does not override or implement a method from a supertype
    Error:Error:line (78)java: method does not override or implement a method from a supertype
    Error:Error:line (84)java: method does not override or implement a method from a supertype
    Error:Error:line (90)java: method does not override or implement a method from a supertype
    Error:Error:line (105)java: method does not override or implement a method from a supertype
    Error:Error:line (110)java: method does not override or implement a method from a supertype
    Error:Error:line (115)java: method does not override or implement a method from a supertype
    Error:Error:line (120)java: method does not override or implement a method from a supertype
    Error:Error:line (126)java: method does not override or implement a method from a supertype
    Error:Error:line (132)java: method does not override or implement a method from a supertype
    Error:Error:line (138)java: method does not override or implement a method from a supertype
    Error:Error:line (144)java: method does not override or implement a method from a supertype
    Error:Error:line (150)java: method does not override or implement a method from a supertype
    Error:Error:line (156)java: method does not override or implement a method from a supertype
    Error:Error:line (162)java: method does not override or implement a method from a supertype
    Error:Error:line (168)java: method does not override or implement a method from a supertype
    Error:Error:line (176)java: method does not override or implement a method from a supertype
    Error:Error:line (181)java: method does not override or implement a method from a supertype
C:\Users\Niklas\Desktop\axon-server-se\axonserver-query-parser\src\main\java\io\axoniq\axonserver\queryparser\EventStoreQueryParser.java
    Error:Error:line (13)java: cannot find symbol
  symbol:   class EventStoreQueryLexer
  location: package io.axoniq
    Error:Error:line (29)java: cannot find symbol
  symbol:   class EventStoreQueryLexer
  location: class io.axoniq.axonserver.queryparser.EventStoreQueryParser
    Error:Error:line (29)java: cannot find symbol
  symbol:   class EventStoreQueryLexer
  location: class io.axoniq.axonserver.queryparser.EventStoreQueryParser
    Error:Error:line (41)java: cannot find symbol
  symbol:   class EventStoreQueryParser
  location: package io.axoniq
    Error:Error:line (41)java: cannot find symbol
  symbol:   class EventStoreQueryParser
  location: package io.axoniq
    Error:Error:line (44)java: package io.axoniq.EventStoreQueryParser does not exist`

**Comment by MGathier** [comment]
There are 2 modules in AxonServer that generate code (axonserver-grpc generates protobuf/java mappings and axonserver-query-processer generates code based on the antlr grammar). IntelliJ does not generate this code when you open the project, so you have to run a maven compile action to get all the code generated.
