### ISSUE TITLE
IndexManager temporary file never deleted if it exists

### ISSUE THREAD

**Issue by Niklas-Peter** [AxonIQ/axon-server-se#45]
https://github.com/AxonIQ/axon-server-se/blob/9479d1e42cda78c0abfbd6623cc6d06cfe4abd87/axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/IndexManager.java#L56

If the temporary index file exists, it will throw immediately without calling FileUtils. 
If the temporary index file does NOT exist, FileUtils will return true without having done anything before.

Should it not be like this?
`if (tempFile.exists() && !FileUtils.delete(tempFile)) {`

**Comment by abuijze** [comment]
Thanks for reporting, @Niklas-Peter! It will be fixed in 4.2, which we expect to be able to release shortly.
