### ISSUE TITLE
Spring: generated password is for development use only.

### ISSUE THREAD

**Issue by ViliusS** [AxonIQ/axon-server-se#467]
After Spring upgrade Axon Server SE 4.5.11 now generated this warning on every start:

Using generated security password: 5efa47cd-2e31-4df2-bf5f-84339c2c1a7f
This generated password is for development use only. Your security configuration must be updated before running your application in production.

**Comment by MGathier** [comment]
This warning is caused by the upgrade to a later Spring Boot version and it is only displayed when you are running Axon Server with access control disabled. If you want to get rid of this message you can set the property:
spring.security.user.password=<anypassword>
for Axon Server.

**Comment by ViliusS** [comment]
Thanks. We have configured Access Control and this message is gone now.
