### ISSUE TITLE
Inconsistent writes

### ISSUE THREAD

**Issue by Morlack** [AxonIQ/axon-server-se#495]
When writing events to Axon Server sometimes events are written that are then available in the complete event stream, but not in an aggregate-specific event stream. The issue does not occur while using Enterprise edition.

Someone has supplied us with a Docker container, specifically designed to cause this issue. It can do so quite reliably. In order to run it, run the following:

`docker run --rm -e AxonServer__Endpoint=http://192.168.50.185:8124 robindv/axonserver-tester:latest`

Replace the endpoint with your external IP, since it is docker. 

What happens is that the events were written:
![image](https://user-images.githubusercontent.com/3278878/168277870-d8ca8a8e-d905-42cc-a0ff-4d29184ee964.png)

However, for the specific aggregate the events are not there:
![image](https://user-images.githubusercontent.com/3278878/168277900-a8e93bf9-349a-4ac3-9b81-025572f32a0a.png)

After a restart, the events are present.

**Comment by MGathier** [comment]
Fix included in 4.5.16/4.6.0
