### ISSUE TITLE
doc problem

### ISSUE THREAD

**Issue by xiawanyingtest** [AxonIQ/axon-server-se#61]
1.How to make the axonservice highly available?
modify   replicas: 1  like this  -> replicas: 10 ???
-------------------------------------------------------
axonserver.yml

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: axonserver
  labels:
    app: axonserver
spec:
  serviceName: axonserver
  replicas: 10
  selector:
    matchLabels:
      app: axonserver
  template:
    metadata:
      labels:
        app: axonserver
    spec:
      containers:
      - name: axonserver
        image: axoniq/axonserver
        imagePullPolicy: Always
        ports:
        - name: grpc
          containerPort: 8124
          protocol: TCP
        - name: gui
          containerPort: 8024
          protocol: TCP
        readinessProbe:
          httpGet:
            port: 8024
            path: /actuator/health
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  name: axonserver-gui
  labels:
    app: axonserver-gui
spec:
  ports:
  - name: gui
    port: 8024
    targetPort: 8024
  selector:
    app: axonserver
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: axonserver
  labels:
    app: axonserver
spec:
  ports:
  - name: grpc
    port: 8124
    targetPort: 8124
  clusterIP: None
  selector:
    app: axonserver

**Comment by MGathier** [comment]
Updating the number of replicas in the kubernetes configuration will start multiple instances of Axon Server, but they will all be independent, and as applications will only connect to one of the instances, messages may not be sent from one application to another if they are connected to another independent Axon Server. 

For high availability and clustering of Axon Server instances, you will need Axon Server Enterprise Edition.
