### ISSUE TITLE
Better usage()  support for possible commands

### ISSUE THREAD

**Issue by jangalinski** [AxonIQ/axon-server-se#93]
When I run the jar without parameters, I get the list of all possible commands. So far so good.
But: the commands are in random order, it's hard to find a particular command. 
If they would just be in alphabetical order, commands like `register-application` and `delete-application` would not be connected.

Feature wish: List commands in logical groups (applications, contexts, users, ...)

**Comment by jangalinski** [comment]
Would you mind adding a comment? Irrelevant? Already fixed, ....

**Comment by MGathier** [comment]
Fixed in 4.2.3.
